import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthiumProvider } from "authium-next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthiumProvider config={{
          // test keys, rotated after every release
          appId: process.env.NEXT_PUBLIC_APP_ID || "",
          apiKey: process.env.NEXT_PUBLIC_API_KEY || "",
        }}>
          {children}
        </AuthiumProvider>
      </body>
    </html>
  );
}
